# Generated by Django 3.0.4 on 2020-04-01 20:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='center'),
        ),
    ]
