# Generated by Django 3.0.4 on 2020-04-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20200401_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='fips',
            field=models.CharField(default=0, max_length=2, null=True, verbose_name='FIPS Код'),
        ),
    ]
