# Generated by Django 3.0.4 on 2020-04-04 21:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_auto_20200402_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='description',
            field=models.TextField(default='', help_text='Описание', max_length=20000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='country',
            name='area',
            field=models.IntegerField(default=0, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='town',
            name='alternatenames',
            field=models.CharField(default='', help_text='Алтернативные названия, разделенные запятой, ascii names automatically transliterated, convenience attribute from alternatename table', max_length=10000, verbose_name='Алтернативные названия'),
        ),
        migrations.AlterField(
            model_name='town',
            name='asciiname',
            field=models.CharField(default='', help_text='Название географической точки  в простых ascii символах', max_length=200, verbose_name='Ascii название'),
        ),
        migrations.AlterField(
            model_name='town',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.Country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='town',
            name='country_code',
            field=models.CharField(default='', help_text='ISO-3166 2-буквенный код страны', max_length=2, verbose_name='Код страны'),
        ),
        migrations.AlterField(
            model_name='town',
            name='elevation',
            field=models.IntegerField(default=0, help_text='elevation in meters', verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='town',
            name='geonameid',
            field=models.IntegerField(default=0, help_text='Id в базе geonames', verbose_name='Geonameid'),
        ),
        migrations.AlterField(
            model_name='town',
            name='modification_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='date of last modification in yyyy-MM-dd format', verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(default='', help_text='Название точки на карте', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='town',
            name='population',
            field=models.IntegerField(default=0, verbose_name='Население'),
        ),
        migrations.AlterField(
            model_name='town',
            name='timezone',
            field=models.CharField(default='', help_text='the iana timezone id(see file timeZone.txt)', max_length=40, verbose_name='Часовой пояс'),
        ),
        migrations.CreateModel(
            name='TownImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos', verbose_name='Фотография')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Town', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
